name: Build Check

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Install Cassandra C++ driver
        wget https://downloads.datastax.com/cpp-driver/ubuntu/20.04/cassandra/v2.16.2/cassandra-cpp-driver_2.16.2-1_amd64.deb
        wget https://downloads.datastax.com/cpp-driver/ubuntu/20.04/cassandra/v2.16.2/cassandra-cpp-driver-dev_2.16.2-1_amd64.deb
        sudo dpkg -i cassandra-cpp-driver_2.16.2-1_amd64.deb
        sudo dpkg -i cassandra-cpp-driver-dev_2.16.2-1_amd64.deb

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Compile extension
      run: bundle exec rake compile

    - name: Run linting
      run: bundle exec rake standard